from pydantic import BaseModel

# Les autres schémas SQLAlchemy sont commentés (migration vers SQL brut)
# from datetime import datetime
# from typing import List, Optional
# class SensorReadingOut(BaseModel): ...
# class AlertOut(BaseModel): ...
# class HiveOut(BaseModel): ...
# class ThresholdUpdate(BaseModel): ...
# class DiagnosisRequest(BaseModel): ...
# class DiagnosisResult(BaseModel): ...


class PushSubscriptionIn(BaseModel):
    subscription: dict
